apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: {{ .Values.cast_service.replicas | default 1 }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      initContainers:
      - name: wait-for-cast-db
        image: busybox
        command:
        - sh
        - -c
        - 'until nc -z {{ .Values.cast_service.initContainers.dbHost }} {{ .Values.cast_service.initContainers.dbPort }}; do echo "Waiting for {{ .Values.cast_service.initContainers.dbHost }}"; sleep 1; done'
      containers:
      - name: "cast-service"
        image: {{ .Values.cast_service.image }}:{{ .Values.cast_service.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c", "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]
        ports:
        - containerPort: {{ .Values.cast_service.port }}
        env:
        - name: DATABASE_URI
          value: {{ .Values.cast_service.env.DATABASE_URI | default "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev" }}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: {{ .Values.cast_service.port }}
