apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configMapName }}
data:
  default.conf: |
    server {
      listen 9090;

      location /api/v1/movies {
        proxy_pass http://movie-service:8002/api/v1/movies;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        error_log /var/log/nginx/error.log debug;  # Enable detailed logging
        }
      location /api/v1/casts {
        proxy_pass http://cast-service:8001/api/v1/casts;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        error_log /var/log/nginx/error.log debug;  # Enable detailed logging
        }
    }
